{
 "title": "bigcord",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "go_jobs",
    "query": {
     "query": "label_values({__name__=~\"go_.+\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Messages",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(scraping_messages_total)"
    }
   ]
  },
  {
   "title": "Messages Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(scraping_messages_total[$__rate_interval])",
     "legendFormat": "{{channel_type}} - {{channel_id}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(scraping_discord_requests_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "HTTP Receive Latency",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(le) (rate(scraping_discord_request_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Clickhouse Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Go: $go_jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }, "repeat": "go_jobs" },
  {
   "title": "Go Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$go_jobs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Memstats Sys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"$go_jobs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go CPU Seconds/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$go_jobs\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "go_threads{job=\"$go_jobs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}