global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "clickhouse"
    scrape_interval: 5s
    static_configs:
      - targets: ["clickhouse:9363"]

  - job_name: "scraping"
    scrape_interval: 5s
    static_configs:
      - targets: [ "scraping:9090" ]
